// <auto-generated />
using System;
using BTrack.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BTrack.Migrations
{
    [DbContext(typeof(BTrackContext))]
    partial class BTrackContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BTrack.Models.Account", b =>
                {
                    b.Property<int>("accountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("accountId"));

                    b.Property<string>("accountName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("accountId");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("BTrack.Models.Bugs", b =>
                {
                    b.Property<int>("bugId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("bugId"));

                    b.Property<string>("bugDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("bugPriority")
                        .HasColumnType("int");

                    b.Property<int>("bugStatus")
                        .HasColumnType("int");

                    b.Property<string>("bugTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("bugId");

                    b.ToTable("Bugs");
                });

            modelBuilder.Entity("BTrack.Models.Login", b =>
                {
                    b.Property<string>("username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("username");

                    b.ToTable("Login");
                });

            modelBuilder.Entity("BTrack.Models.Update", b =>
                {
                    b.Property<int>("updateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("updateId"));

                    b.Property<int>("accountId")
                        .HasColumnType("int");

                    b.Property<int>("bugId")
                        .HasColumnType("int");

                    b.Property<DateTime>("updateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("updateDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("updateId");

                    b.ToTable("Update");
                });
#pragma warning restore 612, 618
        }
    }
}
